version: "3.8"

services:
  dev:
    image: node:18
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx_container
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - dev
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
