version: '3.7'

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "8080:80"  # Map port 8080 on your local machine to port 80 inside the container
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Map nginx.conf from your repo to Nginx container
    networks:
      - dev-network

  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main
    container_name: front_end
    ports:
      - "9080:9080"  # Make sure this port is exposed correctly
    volumes:
      - ./adapter:/source/adapter  # Map the 'adapter' folder to the container
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge
